data:
  X_train: '04_01_data_split/X_train.csv'
  X_val: '04_01_data_split/X_val.csv'
  X_test: '04_01_data_split/X_test.csv'
  y_train: '04_01_data_split/y_train.csv'
  y_val: '04_01_data_split/y_val.csv'
  y_test: '04_01_data_split/y_test.csv'